#!/bin/bash
if mountpoint -q /target; then 
	echo "Installing docker to /target"
	cp /go/src/github.com/docker/docker/bundles/1.3.0/binary/docker-1.3.0 /target
else
	echo "/target is not a mountpoint."
	echo "You can either:" 
	echo "- re-run this container with -v /usr/local/bin:/target" 
	echo "- extract the docker binary (located at /go/src/github.com/docker/docker/bundles/1.3.0/binary/docker-1.3.0)"
fi
